spring:
  application:
    name: aop-log
  aop:
    proxy-target-class: true

server:
  port: 12002

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:debian.shawearn.com}:${eureka.server.port:3183}/eureka/

logging:
  file: ${spring.application.name}.log