spring:
  application:
    name: eureka-provider

server:
  port: 12000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:debian.shawearn.com}:${eureka.server.port:3183}/eureka/

logging:
  file: ${spring.application.name}.log