spring:
  application:
    name: eureka-consumer-feign

server:
  port: 12001

eureka:
  client:
    serviceUrl:
      defaultZone: http://debian.shawearn.com:3183/eureka/

logging:
  file: ${spring.application.name}.log