spring:
  application:
    name: eureka-server

server:
  port: 3183                         # 指定该Eureka实例的端口

eureka:
  instance:
    hostname: localhost            # 指定该Eureka实例的主机名
    lease-renewal-interval-in-seconds: 30       # 租约刷新时间间隔（秒）
    lease-expiration-duration-in-seconds: 40    # 租约到期时间（秒）

  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false   # 关闭自保护

logging:
  file: ${spring.application.name}.log
